export const FORM_WORKSPACE_LOAD_FROM = 'FORM_WORKSPACE_LOAD_FROM';
export const FORM_WORKSPACE_SAVE_AS = 'FORM_WORKSPACE_SAVE_AS';
export const VIEW_BOARD = 'VIEW_BOARD';
export const VIEW_LIBRARY = 'VIEW_LIBRARY';
