export const FORM_WORKSPACE_LOAD_FROM = 'FORM_WORKSPACE_LOAD_FROM'
export const FORM_WORKSPACE_SAVE_AS = 'FORM_WORKSPACE_SAVE_AS'
export const VIEW_BOARD = 'VIEW_BOARD'
export const VIEW_LIBRARY = 'VIEW_LIBRARY'
export const VIEW_STORIES = 'VIEW_STORIES'

export const VIEW_CYCLE = [VIEW_STORIES, VIEW_LIBRARY, VIEW_BOARD]
